#GET
GET http://localhost:8087/api/v1/usuario
Content-Type: application/json
###

#POST
POST http://localhost:8087/api/v1/usuario
Content-Type: application/json

{   
    "nome":"Catalunha",
    "senha":"321",
    "email":"cacau@gmail.com"
}
###

#PUT
PUT http://localhost:8087/api/v1/usuario
Content-Type: application/json

{
    "idUsuario":2,
    "nome":"Cataluinha",
    "senha":"321",
    "email":"cacau@gmail.com"
}
###

#DELETE
DELETE http://localhost:8087/api/v1/usuario/3
Content-Type: application/json